services:
  demo:
    image: push.lovestory.cyou/abhors/demo:latest
    container_name: demo-container
    ports:
      - "8080:8080"
      - "9998:9998"
    volumes:
      - /data/applogs/xxl-job/jobhandler:/data/applogs/xxl-job/jobhandler
    restart: always