brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH

# 自动创建 Topic，生产环境建议关闭
autoCreateTopicEnable = true

# 关键配置：如果是云服务器，这里一定要填公网IP
# brokerIP1 = 127.0.0.1
brokerIP1 = 192.168.51.78