# 遵循文档：不写 kind，不写 name，直接以 steps 开头
steps:
  - name: Java 构建
    image: docker.m.daocloud.io/library/maven:3.9.6-eclipse-temurin-17
    pull: true
    commands:
      - mvn clean package -DskipTests
    volumes:
      - /tmp/maven-cache:/root/.m2
    when:
      event: [ push, pull_request, manual ]
      branch: master

  - name: 镜像构建与推送
    image: docker.m.daocloud.io/woodpeckerci/plugin-docker-buildx:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      repo: registry.cn-zhangjiakou.aliyuncs.com/abhors/demo
      tags: latest
      registry: registry.cn-zhangjiakou.aliyuncs.com
      username:
        from_secret: aliyun_acr_username
      password:
        from_secret: aliyun_acr_password
      mirror: https://docker.m.daocloud.io
    when:
      event: [push, pull_request, manual]
      branch: master