# 第 102 次部署
steps:
  - name: Java 构建
    image: library/maven:3.9.6-eclipse-temurin-17
    pull: true
    commands:
      - mvn clean package -DskipTests
    volumes:
      - /tmp/maven-cache:/root/.m2
    when:
      event: [push, pull_request]
      branch: master

  - name: 构建与推送
    image: woodpeckerci/plugin-docker-buildx:latest-insecure
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      repo: push.lovestory.cyou/abhors/demo
      registry: push.lovestory.cyou
      username:
        from_secret: NEXUS_DOCKER_USERNAME
      password:
        from_secret: NEXUS_DOCKER_PASSWORD
      mirror: https://registry.lovestory.cyou
    when:
      event: push
      branch: master